### ISSUE TITLE
Typo in colophon page “optimsiations” → “optimisations”

### ISSUE THREAD

**Issue by engyii** [MaggieAppleton/maggieappleton.com-V2#17]
_Dunno if it's proper etiquette to create an issue on the source code of your website for such a small, nothing, issue. Split between wanting to help and looking like a jerk (probably the latter :) )_

The tiny typo is here : https://github.com/MaggieAppleton/maggieappleton.com-V2/blob/a8a10c7b6f6704868d0ddfe2a28b36f3441aeeb6/pages/colophon.js#L62

**Comment by MaggieAppleton** [comment]
Appreciate it! Just fixed
